### ISSUE TITLE
Sign-Up Page Error

### ISSUE THREAD

**Issue by SaurabhAgarwala** [SaurabhAgarwala/pastebin#1]
The functionality of sign-up is not working. Nothing happens on clicking the sign-up button after entering the required details. Help in the problem will be highly appreciated.

**Comment by manaswinidas** [comment]
I'm interested

**Comment by SaurabhAgarwala** [comment]
Sure...go ahead...👍

**Comment by SaurabhAgarwala** [comment]
Fixed in #5
